### ISSUE TITLE
v2.1.2 generated constructor has mismatched casing.

### ISSUE THREAD

**Issue by jmauerhan** [martin-helmich/php-schema2class#57]
I just installed the latest version and the code it generated for the constructor looks like this:

```
    /**
     * @param string[] $allUserFollowedTags
     * @param int $numTags
     * @param string[] $tags
     * @param string $userUid
     */
    public function __construct(array $allUserFollowedTags, int $numTags, array $tags, string $userUid)
    {
        $this->all_user_followed_tags = $all_user_followed_tags;
        $this->num_tags = $num_tags;
        $this->tags = $tags;
        $this->user_uid = $user_uid;
    }
```

The casing in the constructor is wrong, and goes from camelCase to snake_case.

**Comment by abienvenu** [comment]
Thank you both for the bug report and the fix. It think this deserves a new release (2.1.3 maybe), so random people (like me) will not stumble into this bug.

**Comment by martin-helmich** [comment]
@abienvenu Thanks for the push -- Now that #58 is merged (although I can't remember why I've let that PR sit for so long... 🤔), I'll prepare a new release shortly.

**Comment by abienvenu** [comment]
Thank you @martin-helmich, schema2class is a very useful tool. I am glad to see that release 2.1.3 is now available :)
